name: Python Lint and Test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.6"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # Run unittests first, because they don't require any dependencies, and we can fail-fast without
    # continuing to `pip` steps.
    - name: Test with unittest
      run: |
        python3 -m unittest *test.py
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install black mypy
    - name: Lint with black
      run: |
        black --config pyproject.toml --check --diff .
    - name: Type check with mypy
      run: |
        mypy .
